# === Configuración principal ===
validation_csv: "monitoring_drift/base_validation_features.csv"
target_col: "__y__"

mlflow:
  tracking_uri: "http://34.209.6.113/"
  experiment: "/equipo30-xgboost"
  username: "admin"
  password: "quail3guru*ongoing"
  model_uri: "models:/absenteeism-predic/1"

# === Simulación del DRIFT ===
drift:
  mean_shifts:
    PCA_1: 0.5
    PCA_2: -0.3
  zero_out_features:
    - "Reason_Category_3.0"
  noise:
    std_fraction: 0.10
  sample_fraction: 1.0

thresholds:
  mae_delta_abs: 0.50
  rmse_delta_abs: 0.60
  r2_drop_abs: 0.05

outputs_dir: "artifacts/drift_run"

